title: AfricanCOMMONS
description: A platform to showcase re-useable tools built across Africa and the people & organizations building them.

url: https://africancommons.net
enforce_ssl: africancommons.net

google_analytics: UA-44795600-36
